name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

     - name: Install Gradle Manually
  run: |
    wget https://services.gradle.org/distributions/gradle-8.3-bin.zip
    unzip gradle-8.3-bin.zip
    mv gradle-8.3 gradle
    chmod +x gradle/bin/gradle


      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
